// Package hmf implements Hearth Map Format v1 (HMF v1): the chunked tile
// format, the frozen editor op stream, and the pure grid application rules.
//
// HMF v1 is the ONLY map format in Hearth — there is no import path. Every
// mutation of a world is one frozen protocol op (paint|erase|place|zone|
// portal|publish) and worlds are stored as 16x16 RLE-encoded chunks in
// SQLite (see docs/HMF-v1.md for the full RFC).
//
// This package is deliberately free of I/O and of the server's World type so
// it can be shared by the server (server/*.go) and the showcase fixture
// builder (cmd/showcase) — the dogfood worlds are generated by APPLYING op
// streams through the exact same code path the live server uses.
package hmf

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
)

// ChunkSize is the HMF v1 chunk edge length in tiles (16x16 = 256 cells).
const ChunkSize = 16

// ChunkCells is the number of cells in one chunk.
const ChunkCells = ChunkSize * ChunkSize

// MaxCellsPerOp caps a single batch op (fill/rect/line can be large).
const MaxCellsPerOp = 4096

// FloorTile is the implicit base tile: never stored, never serialized.
const FloorTile = 0

// Palette is the FROZEN HMF v1 tile palette: canonical tile name -> numeric
// id. 0 = floor (implicit base, never stored). Adding or renumbering a tile
// is a protocol change (docs/HMF-v1.md) — the server (world.go) and the
// client editor (tiles.ts) mirror this exactly.
var Palette = map[string]int{
	"floor": 0, "wall": 1, "water": 2, "grass": 3, "stone": 4,
	"sand": 5, "path": 6, "wood": 7, "lava": 8, "ice": 9,
	"flower": 10, "bush": 11, "rock": 12, "tree": 13, "roof": 14,
	"door": 15, "fence": 16, "bridge": 17, "crystal": 18, "dirt": 19,
}

// PassableSet marks which tiles allow walking. Collision flags in HMF v1 are
// derived from this at build time — the palette is the single source of
// truth for passability.
var PassableSet = map[string]bool{
	"floor": true, "grass": true, "stone": true, "sand": true,
	"path": true, "wood": true, "ice": true, "flower": true,
	"dirt": true, "bridge": true,
}

var nameByID = func() map[int]string {
	m := make(map[int]string, len(Palette))
	for n, id := range Palette {
		m[id] = n
	}
	return m
}()

// TileID returns the numeric palette id for a tile name (0 for unknown).
// Lenient by design for callers that treat unknown names as floor.
func TileID(name string) int {
	if id, ok := Palette[name]; ok {
		return id
	}
	return FloorTile
}

// TileIDOK is the strict lookup: it reports whether name is a real palette
// entry. Callers that must NOT silently turn an unknown name into floor
// (e.g. the editor op parser, the fixture builder) use this and reject.
func TileIDOK(name string) (int, bool) {
	id, ok := Palette[name]
	return id, ok
}

// TileName returns the palette name for a numeric id ("" for unknown).
func TileName(id int) string {
	return nameByID[id]
}

// TileNames returns the id -> name reverse palette (shared, read-only).
func TileNames() map[int]string { return nameByID }

// Passable reports whether a tile name allows walking.
func Passable(name string) bool { return PassableSet[name] }

// ErrTooManyCells is returned when a batch op exceeds MaxCellsPerOp.
var ErrTooManyCells = errors.New("hmf: op exceeds max cells per op")

// Cell is one tile coordinate.
type Cell struct {
	X int `json:"x"`
	Y int `json:"y"`
}

// Portal is a portal op payload / persisted portal row.
type Portal struct {
	ID          string `json:"id"`
	X           int    `json:"x"`
	Y           int    `json:"y"`
	TargetSpace string `json:"targetSpace"`
	TargetX     int    `json:"targetX"`
	TargetY     int    `json:"targetY"`
}

// Zone is a zone op payload / persisted zone row (named rect region).
type Zone struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	X    int    `json:"x"`
	Y    int    `json:"y"`
	W    int    `json:"w"`
	H    int    `json:"h"`
}

// Op is one frozen HMF v1 editor operation. Every mutation of a world is an
// Op; ops are server-arbitrated (LWW by arrival order) and persisted to the
// op_log for replay / build history.
type Op struct {
	// Op is the frozen op kind: paint|erase|place|zone|portal|publish|chunk_get.
	Op string `json:"op"`

	// Single-cell ops use X/Y; batch ops (fill/rect/line) use Cells.
	X      int    `json:"x,omitempty"`
	Y      int    `json:"y,omitempty"`
	TileID int    `json:"tileId,omitempty"`
	Cells  []Cell `json:"cells,omitempty"`

	// Portal placement (add/upsert) or PortalID-only for removal.
	Portal   *Portal `json:"portal,omitempty"`
	PortalID string  `json:"portalId,omitempty"`

	// Zone placement (add/upsert) or ZoneID-only for removal.
	Zone   *Zone  `json:"zone,omitempty"`
	ZoneID string `json:"zoneId,omitempty"`

	// Chunk fetch (chunk_get request): which chunk the client wants.
	CX int `json:"cx,omitempty"`
	CY int `json:"cy,omitempty"`

	// UndoOf references the server seq of the op this op compensates.
	UndoOf int64 `json:"undoOf,omitempty"`

	// Idem is the optional idempotency key (agent-facing op-log contract,
	// docs/BOT-PROTOCOL.md): "<bot_run_id>:<op_index>". When set, the server
	// dedupes replays — an op already applied under the same key (space_id,
	// idem) is acknowledged with deduped:true instead of being re-applied.
	// Humans/legacy clients never send it ("" = no dedupe).
	Idem string `json:"idem,omitempty"`

	// Seq is the server-assigned monotonic op seq (per space). Filled by the
	// server on apply; the op_log key is (space_id, seq).
	Seq int64 `json:"seq,omitempty"`

	// By is the acting session/entity id, filled by the server on apply.
	By string `json:"by,omitempty"`

	// Actor is the acting user id (sha256(deviceKey)) — the account the op is
	// attributed to in the audit trail (op_log payload + activity_events).
	// Filled by the server on apply; bots are attributed to their bot account.
	Actor string `json:"actor,omitempty"`

	// SpaceID is the target space, filled/validated by the server.
	SpaceID string `json:"spaceId,omitempty"`
}

// CellChange is the result of applying one cell of an op: the tile that was
// written and the tile that was there before (for compensating inverse ops).
type CellChange struct {
	X      int `json:"x"`
	Y      int `json:"y"`
	TileID int `json:"tileId"`
	Prior  int `json:"priorTileId"`
}

// Grid is a sparse tile map: "x,y" -> tileId (0/absent = floor).
type Grid map[string]int

// Key builds the sparse-grid key for a cell.
func Key(x, y int) string { return fmt.Sprintf("%d,%d", x, y) }

// ChunkOf returns the chunk coordinates containing tile (x,y).
// Uses floor division: Go's / truncates toward zero, so x = -1 would map to
// chunk 0 instead of -1. All current callers reject negative coordinates
// before calling, but this package is documented as pure and shared.
func ChunkOf(x, y int) (cx, cy int) { return floorDiv(x, ChunkSize), floorDiv(y, ChunkSize) }

// floorDiv divides rounding toward negative infinity (Go's / truncates).
func floorDiv(a, b int) int {
	q := a / b
	if a%b != 0 && (a < 0) != (b < 0) {
		q--
	}
	return q
}

// ChunkOrigin returns the world-space origin tile of a chunk.
func ChunkOrigin(cx, cy int) (x0, y0 int) { return cx * ChunkSize, cy * ChunkSize }

// ApplyOp applies one grid op (paint|erase|place-with-tile) to the sparse
// grid, last-write-wins per cell. Returns the changed cells with their prior
// tile ids so callers can build compensating inverse ops (undo) and bump
// chunk revisions. Ops that touch no grid cells (portal/zone/publish/
// chunk_get) return an empty change list — the server handles those.
func ApplyOp(g Grid, w, h int, op *Op) ([]CellChange, error) {
	if op == nil {
		return nil, errors.New("hmf: nil op")
	}
	// Only grid ops (paint|erase|place) mutate the tile grid. portal/zone/
	// publish/chunk_get are handled by the server, not the grid applier.
	switch op.Op {
	case "paint", "erase", "place":
	case "":
		return nil, errors.New("hmf: op kind required")
	default:
		return nil, nil
	}
	cells := op.Cells
	if len(cells) == 0 {
		cells = []Cell{{X: op.X, Y: op.Y}}
	}
	if len(cells) > MaxCellsPerOp {
		return nil, ErrTooManyCells
	}
	tid := op.TileID
	if op.Op == "erase" {
		tid = FloorTile
	}
	if tid < 0 || tid > 255 {
		return nil, fmt.Errorf("hmf: tileId %d out of range", tid)
	}
	var out []CellChange
	for _, c := range cells {
		if c.X < 0 || c.Y < 0 || c.X >= w || c.Y >= h {
			return nil, fmt.Errorf("hmf: cell (%d,%d) outside %dx%d world", c.X, c.Y, w, h)
		}
		k := Key(c.X, c.Y)
		prior := g[k]
		if prior == tid {
			continue // no change — keep chunk revs stable
		}
		if tid == FloorTile {
			delete(g, k)
		} else {
			g[k] = tid
		}
		out = append(out, CellChange{X: c.X, Y: c.Y, TileID: tid, Prior: prior})
	}
	return out, nil
}

// EncodeChunk renders the full 256-cell grid of chunk (cx,cy) from the sparse
// world grid. Cells outside the world bounds are floor (never stored).
func EncodeChunk(g Grid, w, h int, cx, cy int) [ChunkCells]int {
	var grid [ChunkCells]int
	x0, y0 := ChunkOrigin(cx, cy)
	for i := 0; i < ChunkCells; i++ {
		x := x0 + i%ChunkSize
		y := y0 + i/ChunkSize
		if x < 0 || y < 0 || x >= w || y >= h {
			continue
		}
		grid[i] = g[Key(x, y)]
	}
	return grid
}

// EncodeRLE compresses a 256-cell chunk grid to "tileId:count,..." pairs.
// The pairs always total exactly 256 cells.
func EncodeRLE(grid [ChunkCells]int) string {
	var parts []string
	i := 0
	for i < ChunkCells {
		v := grid[i]
		j := i
		for j < ChunkCells && grid[j] == v {
			j++
		}
		parts = append(parts, strconv.Itoa(v)+":"+strconv.Itoa(j-i))
		i = j
	}
	return strings.Join(parts, ",")
}

// DecodeRLE expands an RLE string back to a 256-cell chunk grid.
func DecodeRLE(s string) ([ChunkCells]int, error) {
	var grid [ChunkCells]int
	if s == "" {
		return grid, nil // all floor
	}
	idx := 0
	for _, part := range strings.Split(s, ",") {
		kv := strings.SplitN(part, ":", 2)
		if len(kv) != 2 {
			return grid, fmt.Errorf("hmf: bad rle segment %q", part)
		}
		v, err1 := strconv.Atoi(kv[0])
		n, err2 := strconv.Atoi(kv[1])
		if err1 != nil || err2 != nil || v < 0 || v > 255 || n < 0 || idx+n > ChunkCells {
			return grid, fmt.Errorf("hmf: bad rle segment %q", part)
		}
		for k := 0; k < n; k++ {
			grid[idx+k] = v
		}
		idx += n
	}
	if idx != ChunkCells {
		return grid, fmt.Errorf("hmf: rle covers %d cells, want %d", idx, ChunkCells)
	}
	return grid, nil
}

// ChunkTileCells extracts the non-floor cells of a chunk that lie inside the
// world bounds as {x,y,tileId} changes (Prior unused) for the client.
func ChunkTileCells(grid [ChunkCells]int, cx, cy, w, h int) []CellChange {
	x0, y0 := ChunkOrigin(cx, cy)
	var out []CellChange
	for i := 0; i < ChunkCells; i++ {
		x := x0 + i%ChunkSize
		y := y0 + i/ChunkSize
		if x < 0 || y < 0 || x >= w || y >= h {
			continue
		}
		v := grid[i]
		if v != FloorTile {
			out = append(out, CellChange{X: x, Y: y, TileID: v})
		}
	}
	return out
}
